In [ ]:
import pandas as pd

df = pd.read_csv('/content/base_original.csv', sep=None, engine='python')

print("Primeiras 5 linhas do DataFrame após correção do separador:")
display(df.head())

print("\nInformações gerais do DataFrame (tipos de dados e valores não nulos) após correção do separador:")
df.info()

Primeiras 5 linhas do DataFrame após correção do separador:

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

Informações gerais do DataFrame (tipos de dados e valores não nulos) após correção do separador:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            25000 non-null  int64
 1   Name               25000 non-null  object
 2   Age                25000 non-null  int64
 3   Country            25000 non-null  object
 4   Subscription_Type  25000 non-null  object
 5   Watch_Time_Hours   25000 non-null  float64
 6   Favorite_Genre     25000 non-null  object
 7   Last_Login         25000 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.5+ MB

Agora que os dados foram carregados corretamente, vamos remover as linhas duplicadas para garantir a unicidade dos registros.

In [ ]:
# Remove as linhas duplicadas
initial_rows = len(df)
df.drop_duplicates(inplace=True)

print(f"Linhas duplicadas removidas: {initial_rows - len(df)}")
print(f"Total de linhas após remover duplicatas: {len(df)}")

Linhas duplicadas removidas: 0
Total de linhas após remover duplicatas: 25000

Com base na verificação anterior, não há valores nulos no DataFrame. Podemos seguir para a remoção de espaços em branco das colunas de texto, que foi uma das suas instruções de limpeza.

In [ ]:
# Remove os espaços em branco das colunas
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip()

print("Espaços em branco removidos das colunas de texto.")
# Exibe as colunas já limpas
display(df.head())

Espaços em branco removidos das colunas de texto.

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

A próxima etapa é padronizar o texto em todas as colunas de tipo `object` (string). Vamos converter o texto para a primeira letra maiúscula para uma melhor consistência.

Para padronizar corretamente o nome e o sobrenome (ou seja, a primeira letra de cada palavra em maiúscula) na coluna 'Name', vamos aplicar a função `str.title()`.

In [ ]:
# Padroniza a coluna 'Name' para que o 'nome' e o 'sobrenome' comecem com a letra maiúscula.
df['Name'] = df['Name'].str.title()

print("Coluna 'Name' padronizada.")
# Exibe as primeiras linhas para confirmar
display(df.head())

Coluna 'Name' padronizada.

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

A coluna `Last_Login` deve ser convertida para o tipo de dado `datetime` para permitir análises baseadas em tempo. Vamos fazer essa conversão agora.

In [ ]:
# A coluna 'Last_Login' é convertida para o tipo de dado 'datetime' para permitir análises baseadas em tempo.
df['Last_Login'] = pd.to_datetime(df['Last_Login'])

print("Tipo de dado da coluna 'Last_Login' convertido para datetime.")

df.info()

display(df.head())

Tipo de dado da coluna 'Last_Login' convertido para datetime.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            25000 non-null  int64
 1   Name               25000 non-null  object
 2   Age                25000 non-null  int64
 3   Country            25000 non-null  object
 4   Subscription_Type  25000 non-null  object
 5   Watch_Time_Hours   25000 non-null  float64
 6   Favorite_Genre     25000 non-null  object
 7   Last_Login         25000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 1.5+ MB

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

## 2. Padronização de Nomes de Colunas

Para facilitar a compreensão e o manuseio dos dados, as colunas foram renomeadas para português, seguindo a convenção `Snake Case`.

In [134]:
df.rename(columns={
    'User_ID': 'ID',
    'Name': 'Nome',
    'Age': 'Idade',
    'Country': 'País',
    'Subscription_Type': 'Assinatura',
    'Watch_Time_Hours': 'Horas_Assistidas',
    'Favorite_Genre': 'Gênero_Favorito',
    'Last_Login': 'Ultimo_'
}, inplace=True)

print("Colunas renomeadas com sucesso.")

display(df.head())
df.info()

Colunas renomeadas com sucesso.

,ID,Nome,Idade,País,Assinatura,Horas_Assistidas,Genero_Favorito,Ultimo_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                25000 non-null  int64
 1   Nome              25000 non-null  object
 2   Idade             25000 non-null  int64
 3   País              25000 non-null  object
 4   Assinatura        25000 non-null  object
 5   Horas_Assistidas  25000 non-null  float64
 6   Genero_Favorito   25000 non-null  object
 7   Ultimo_Login      25000 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.5+ MB

# Relatório de Limpeza e Padronização de Dados

Este relatório detalha as principais características do dataset e as transformações aplicadas para garantir a qualidade e consistência dos dados.

## 1. Visão Geral do Dataset

Após o carregamento e limpeza, o dataset `df` possui as seguintes dimensões:
*   **Número de Linhas:** `len(df)`
*   **Número de Colunas:** `len(df.columns)`

### Tipos de Dados por Coluna

A seguir, a estrutura dos tipos de dados para cada coluna:

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            25000 non-null  int64
 1   Name               25000 non-null  object
 2   Age                25000 non-null  int64
 3   Country            25000 non-null  object
 4   Subscription_Type  25000 non-null  object
 5   Watch_Time_Hours   25000 non-null  float64
 6   Favorite_Genre     25000 non-null  object
 7   Last_Login         25000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 1.5+ MB

In [ ]:
print(f"*   **Número de Linhas:** {len(df)}")
print(f"*   **Número de Colunas:** {len(df.columns)}")

*   **Número de Linhas:** 25000
*   **Número de Colunas:** 8